sudo: required
services:
- docker
script:
- make container
before_deploy:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
deploy:
- provider: script
  script: make push
  on:
    tags: true
env:
  global:
  - secure: a/9ailtKD92pMafVHP/7KThgwIsJ982L2/drlDiHFNxRM7tjTIJRZM7ODMNS2BqG+MSgfa6LjHrCAQxJwgabJI6sbi9ZpgrrsyDsvzJ/Qd8vwK48/N53L7sd5nsDPy6sZytJPgZlQb18X7G+F8Awv4EO3uR6eS1X8MJZ0Vrll5WyOE0mRxmKopqLGIuslA2NSAokE8q+3tEtxxo7CMm/eWQ7Xg9EFiYLNQVSKWEkgiYFPqI8hKv5Op8PNztY9xSf9DhTYIb5uAiUvhPHFKkNBHZ4/O1gI003jk62sGTNltila5TWAtzRQ0PAjGDmRYA15YOddPbGQG+jZK6tuvdUY4YUdWoV3C55wdpjHgVMNgeZ/o2w1zNuJMXgR++PnZFJZPFb7O1FNJ/rVTw9Ak29EfVJNwU0M6vCFpFjvUuenPh9ElcjYsRIJL5SjkzekoSJTZRYGgZ3b+Q5C6GOZOHqOn4SGA0YQ0RM4YSDu9dmbrBjGUMbKNGSE7NWcEQm0VuxmjVqrhy0Bh7aOYl6mKwnTh8n4YJ2C88I/tlYJZYh7CrcTFoT7SPvfR9a+UDCDq/1KzWNL23RGhqjxUtZ9+ub+tg7e/9K3+oStWyIKkM8Bclm+Siey66KTFfuX3vcq8R6X6loGQdqcHo3EX9o5NjKRGuTb7JEK/8nNGy24E4KGxw=
  - secure: lUFlmOdVYQ5ehRo3Cj9yE9enJ/pt82FVyLb1w3B6aB93NB6HrICfeLiBrT++j67PGNsnEexZa6kjOKvQ6UZCCFQMJYR3XMDa2/3e2+otD88jH/3lr2BxEe+trNH72rSzcQKUgVEOCMjFtn1EAEghrwj0F6/5SVqBd8bwwKabjESZtFIOtpd+i8ZL3DCcgCPvpe1UQ0lbbluyMc9UlonAKHKCs4f/An9eevA71mGX+9ZJV+B0G6JyscEF0G18Jco6lSLZVQXhosD2NeD0bb3sQa/59JBXAz/PjK/DHOjrPdcchyuUBJHMGz6CAj17EOTJFHOFO2FIRrMMXrrr2KlG5PtR2xNdbrZC79tzClFfpG/BIG/WmKBWRK3qkJO7YpZyc07ND+1ILVjJxoLlgQCiVLUExqL4zYbFiDEPkZTMtLmPANIQuRsU3YFTO3VuRWxXyX87oT0Ki6cVuJ89QWZY1A4IPKXzDiEOIciqooztNHV4mIkxGxFp1/BmpBElhyU57NlLIOb+FecxJwaX2hjTfz4ZVEc3PLPdV1fbq+AntUaSOMw1cxUrf2AwUX3q01J7FXyy+aWvSZulgsUu2XVeaAF7QP0SuNSkEAWsBCzODVEaXD0EHKG6HuIfVGlEkK0lc2OjS1KW824dtdbHln/xreO83jxpCayktqdvcdNJjIo=
